<?php
/**
 * Public News archive body.
 *
 * @var string $title
 * @var string $description
 * @var array<int,array<string,mixed>> $items
 * @var string $filter_form
 * @var string $pagination
 * @var string $empty_html
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<main id="main-content" class="sabri-news sabri-news-archive">
	<header class="sabri-news-archive__header">
		<p class="sabri-news-eyebrow"><?php echo esc_html__( 'Editorial News', 'sabri-complete-home-news-feed' ); ?></p>
		<h1><?php echo esc_html( $title ); ?></h1>
		<?php if ( ! empty( $description ) ) : ?>
			<p><?php echo esc_html( $description ); ?></p>
		<?php endif; ?>
	</header>
	<?php echo $filter_form; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by controlled plugin renderer. ?>
	<section class="sabri-news-grid" aria-label="<?php echo esc_attr__( 'News articles', 'sabri-complete-home-news-feed' ); ?>">
		<?php
		if ( $items ) {
			foreach ( $items as $item ) {
				echo \Sabri\HomeNewsFeed\NewsPublicRuntime::render_card( $item ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
			}
		} else {
			echo $empty_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		}
		?>
	</section>
	<?php if ( $pagination ) : ?>
		<nav class="sabri-news-pagination" aria-label="<?php echo esc_attr__( 'News pagination', 'sabri-complete-home-news-feed' ); ?>">
			<?php echo $pagination; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
		</nav>
	<?php endif; ?>
</main>
